# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'food-barcode-scanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for food-barcode-scanner

# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Database'

# workaround for cocoapods/swift warning
post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
  end
 end
end

end
